/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import New_Class.Student;
import Service.ClockThread;
import Service.ServiceGrade;
import Service.ServiceStudent;
import com.microsoft.sqlserver.jdbc.SQLServerDataSource;
import com.microsoft.sqlserver.jdbc.SQLServerException;
import java.awt.FileDialog;
import java.awt.Frame;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ButtonGroup;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.TableModel;

/**
 *
 * @author BUI QUANG HIEU
 */
public class MainGUIQuanLySinhVien extends javax.swing.JFrame {

    Service.ServiceStudent _ServiceStudent = new ServiceStudent();
    Service.ServiceGrade serviceGrade = new ServiceGrade();
//    List<Student> _ListStudents = _ServiceStudent.getlstStudent();
//    ServiceStudent _ServiceStudent = new ServiceStudent();
    /**
     * Creates new form MainGUIQuanLySinhVien
     */
    Student _Student;
//    List<Student> _ListStudent = _ServiceStudent._ListStudents;
    DefaultTableModel _DefaultTableModel = new DefaultTableModel();
    String _images = null;
    File _file;
    FileDialog _fd = new FileDialog(new Frame(), "Hình ảnh", FileDialog.LOAD);
    Connection con;

    public MainGUIQuanLySinhVien() throws SQLException {
        this._ServiceStudent = new ServiceStudent();
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        ButtonGroup bg = new ButtonGroup();
        bg.add(rd_nu);
        bg.add(rd_nam);
        rd_nam.setSelected(true);
        con = Connect.ketNoi("ASSIGNMENT");
        if (con != null) {
//            JOptionPane.showMessageDialog(this, "Kết nối thành công");
        } else {
            JOptionPane.showMessageDialog(this, "Kết nối không thành công");
        }
        _ServiceStudent.getListStudentDB();
        LoadTable();
        ClockThread clockThread = new ClockThread(lbl_clock);
        clockThread.start();
        int getIndex = 0;
        if (_ServiceStudent.getlstStudent().isEmpty()) {
            return;
        } else {
            Student st = new Student();
            st = _ServiceStudent.getlstStudent().get(getIndex);
            txt_msv.setText(st.getMsv());
            txt_hoTen.setText(st.getHoTen());
            txt_email.setText(st.getEmail());
            txt_sdt.setText(st.getSdt());
            txt_diaChi.setText(st.getDiaChi());
            if (st.getGioiTinh() == true) {
                rd_nam.setSelected(true);
            } else {
                rd_nu.setSelected(true);
            }

            if (st.getHinhAnh().equalsIgnoreCase("NO IMAGES")) {
                lbl_images.setText("NO IMAGES");
                lbl_images.setIcon(null);
            } else {
                _images = _ServiceStudent.getlstStudent().get(getIndex).getHinhAnh();
                String url = "images\\" + st.getHinhAnh();
                lbl_images.setText("");
                ImageIcon imgIcon = new ImageIcon(url);
                Image img = imgIcon.getImage();
                lbl_images.setIcon(new ImageIcon(img.getScaledInstance(lbl_images.getWidth(), lbl_images.getHeight(), 0)));
                try {
                    lbl_images.setIcon((Icon) img);
                } catch (Exception e) {
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txt_msv = new javax.swing.JTextField();
        txt_hoTen = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        txt_diaChi = new javax.swing.JTextArea();
        txt_email = new javax.swing.JTextField();
        txt_sdt = new javax.swing.JTextField();
        rd_nam = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        rd_nu = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lbl_images = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btn_update = new javax.swing.JButton();
        btn_exit = new javax.swing.JButton();
        btn_new = new javax.swing.JButton();
        btn_save = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        lbl_clock = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbl_student = new javax.swing.JTable();

        jScrollPane1.setViewportView(jEditorPane1);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản Lý Sinh Viên");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowDeactivated(java.awt.event.WindowEvent evt) {
                formWindowDeactivated(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 255));
        jLabel1.setText("Quản Lý Sinh Viên");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Thêm Sinh Viên"));

        txt_msv.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txt_msv.setForeground(new java.awt.Color(0, 51, 255));

        txt_hoTen.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txt_hoTen.setForeground(new java.awt.Color(0, 0, 255));

        txt_diaChi.setColumns(20);
        txt_diaChi.setLineWrap(true);
        txt_diaChi.setRows(5);
        txt_diaChi.setWrapStyleWord(true);
        jScrollPane5.setViewportView(txt_diaChi);

        txt_email.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        txt_sdt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        rd_nam.setText("Nam");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Mã SV: ");

        rd_nu.setText("Nữ");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Họ tên:");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        lbl_images.setText(" IMG (click vào đây)");
        lbl_images.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_imagesMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_images, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_images, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Email:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("SĐT: ");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Giới tính: ");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Địa chỉ: ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(rd_nam)
                                .addGap(18, 18, 18)
                                .addComponent(rd_nu))
                            .addComponent(txt_msv)
                            .addComponent(txt_hoTen)
                            .addComponent(txt_email)
                            .addComponent(txt_sdt, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_msv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txt_hoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40))
                            .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_sdt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addGap(55, 55, 55)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rd_nam)
                    .addComponent(rd_nu)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Chức năng"));

        btn_update.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Edit.png"))); // NOI18N
        btn_update.setText("Update");
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });

        btn_exit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Exit.png"))); // NOI18N
        btn_exit.setText("Exit");
        btn_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_exitActionPerformed(evt);
            }
        });

        btn_new.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_new.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Add.png"))); // NOI18N
        btn_new.setText("New");
        btn_new.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_newActionPerformed(evt);
            }
        });

        btn_save.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Save.png"))); // NOI18N
        btn_save.setText("Save");
        btn_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveActionPerformed(evt);
            }
        });

        btn_delete.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Delete.png"))); // NOI18N
        btn_delete.setText("Delete");
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Clock"));

        lbl_clock.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbl_clock.setForeground(new java.awt.Color(0, 51, 255));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_clock, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_clock, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btn_new, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btn_delete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btn_save, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btn_update, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(btn_exit)
                                .addGap(61, 61, 61))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btn_delete, btn_exit, btn_new, btn_save, btn_update});

        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_new)
                    .addComponent(btn_save))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_delete)
                    .addComponent(btn_update))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_exit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btn_delete, btn_exit, btn_new, btn_save, btn_update});

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông tin Sinh Viên"));

        tbl_student.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã SV", "Họ tên", "Email", "SĐT", "Giới tính", "Địa chỉ", "Hình"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_student.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_studentMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tbl_student);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(310, 310, 310)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(38, 38, 38)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveActionPerformed

        if (checkEmpty() == true) {
            if (!_ServiceStudent.checkName(txt_hoTen.getText())) {
                JOptionPane.showMessageDialog(this, "Họ Tên không chứa kí tự số và kí tự đặc biệt");
            } else if (!_ServiceStudent.checkEmail(txt_email.getText())) {
                JOptionPane.showMessageDialog(this, "Email phải đúng định dạng");
            } else if (!_ServiceStudent.checkSdt(txt_sdt.getText())) {
                JOptionPane.showMessageDialog(this, "SĐT phải đúng theo tiêu chuẩn Việt Nam");
            } else {
                _Student = new Student(txt_msv.getText().toUpperCase(), _ServiceStudent.chuanHoaDanhTuRieng(txt_hoTen.getText()), txt_email.getText(), txt_sdt.getText(), rd_nam.isSelected() ? true : false,
                        txt_diaChi.getText(), lbl_images.getText());
                _Student.setHinhAnh(_images == null ? "NO IMAGES" : _images);
                if (_ServiceStudent.checkMsv(_Student)) {
                    JOptionPane.showMessageDialog(this, "MSV tồn tại !");
                    txt_msv.setText("");
                } else
                    
                    try {
                    int getChoice = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn Thêm không ?", "Thêm", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
                    if (getChoice == JOptionPane.YES_OPTION) {
                        if (_ServiceStudent.addStudent(_Student)) {
                            JOptionPane.showMessageDialog(this, "Thêm thành công");
                            _ServiceStudent.getListStudentDB();
                            LoadTable();
                        } else {
                            JOptionPane.showMessageDialog(this, "Thất bại");
                        }
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(MainGUIQuanLySinhVien.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_btn_saveActionPerformed

    private void btn_newActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_newActionPerformed
        int getChoice = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn New không ?", "Thêm", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (getChoice == JOptionPane.YES_OPTION) {
            clearForm();
        }
    }//GEN-LAST:event_btn_newActionPerformed

    private void lbl_imagesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_imagesMouseClicked
        try {

            _fd.setVisible(true); //mở hộp thoại chọn file
            _file = new File(_fd.getDirectory() + _fd.getFile());
            if (!String.valueOf(_file).equalsIgnoreCase("nullnull")) {
                Image image = ImageIO.read(_file);
                _images = _file.getName();
                lbl_images.setText("");
                int with = lbl_images.getWidth();
                int height = lbl_images.getHeight();
                lbl_images.setIcon(new ImageIcon(image.getScaledInstance(with, height, with)));
                return;
            }

        } catch (IOException ex) {
            Logger.getLogger(MainGUIQuanLySinhVien.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_lbl_imagesMouseClicked

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        int getIndex = tbl_student.getSelectedRow();
        if (getIndex == -1) {
            JOptionPane.showMessageDialog(this, "Mời bạn chọn SV cần xóa");
        } else {
            int getChoice = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn Xóa ?", "Xóa", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (getChoice == JOptionPane.YES_OPTION) {
                if (_ServiceStudent.deleteStudentToDB(txt_msv.getText())) {
                    try {
                        _ServiceStudent.getListStudentDB();
                    } catch (SQLException ex) {
                        Logger.getLogger(MainGUIQuanLySinhVien.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    LoadTable();
                    JOptionPane.showMessageDialog(this, "Xóa thành công");
                } else {
                    JOptionPane.showMessageDialog(this, "Xóa không thành công !");
                }
            }
        }
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        int getIndex = tbl_student.getSelectedRow();
        if (getIndex == -1) {
            JOptionPane.showMessageDialog(this, "Mời bạn chọn SV cần sửa");
            return;
        }
        if (checkEmpty() == true) {
            if (!_ServiceStudent.checkName(txt_hoTen.getText())) {
                JOptionPane.showMessageDialog(this, "Họ Tên không chứa kí tự số và kí tự đặc biệt");
            } else if (!_ServiceStudent.checkEmail(txt_email.getText())) {
                JOptionPane.showMessageDialog(this, "Email phải đúng định dạng");
            } else if (!_ServiceStudent.checkSdt(txt_sdt.getText())) {
                JOptionPane.showMessageDialog(this, "SĐT phải đúng theo tiêu chuẩn Việt Nam");
            } else if (!txt_msv.getText().equalsIgnoreCase(_ServiceStudent.getlstStudent().get(getIndex).getMsv())) {
                JOptionPane.showMessageDialog(this, "MSV không được sửa !");
                return;
            } else {

                int getChoice = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn Sửa ?", "Sửa", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
                if (getChoice == JOptionPane.YES_OPTION) {
                    Student st;
//                    _ServiceStudent._ListStudents.set(getIndex, st = new Student(txt_msv.getText(), _ServiceStudent.chuanHoaDanhTuRieng(txt_hoTen.getText()), txt_email.getText(), txt_sdt.getText(), rd_nam.isSelected() ? true : false, txt_diaChi.getText(), _images == null ? "NO IMAGES" : _images));
//                    Student st = new Student();
                    st = _ServiceStudent.getlstStudent().get(getIndex);
                    st.setMsv(txt_msv.getText().toUpperCase());
                    st.setHoTen(_ServiceStudent.chuanHoaDanhTuRieng(txt_hoTen.getText()));
                    st.setEmail(txt_email.getText());
                    st.setSdt(txt_sdt.getText());
                    st.setDiaChi(txt_diaChi.getText());
                    st.setGioiTinh(rd_nam.isSelected() ? true : false);
                    st.setHinhAnh(_images == null ? "NO IMAGES" : _images);
                    _ServiceStudent.editStudentToDB(st);
                    try {
                        _ServiceStudent.getListStudentDB();
                    } catch (SQLException ex) {
                        Logger.getLogger(MainGUIQuanLySinhVien.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    LoadTable();
                    JOptionPane.showMessageDialog(this, "Bạn đã sửa thành công !");
                } else {
                    JOptionPane.showMessageDialog(this, "Sửa không thành công");
                }

            }
        }
    }//GEN-LAST:event_btn_updateActionPerformed

    private void tbl_studentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_studentMouseClicked
        int getIndex = tbl_student.getSelectedRow();
        Student st = new Student();
        st = _ServiceStudent.getlstStudent().get(getIndex);
        txt_msv.setText(st.getMsv());
        txt_hoTen.setText(st.getHoTen());
        txt_email.setText(st.getEmail());
        txt_sdt.setText(st.getSdt());
        txt_diaChi.setText(st.getDiaChi());
        if (st.getGioiTinh() == true) {
            rd_nam.setSelected(true);
        } else {
            rd_nu.setSelected(true);
        }

        if (st.getHinhAnh().equalsIgnoreCase("NO IMAGES")) {
            lbl_images.setText("NO IMAGES");
            lbl_images.setIcon(null);
        } else {
            _images = _ServiceStudent.getlstStudent().get(getIndex).getHinhAnh();
            String url = "images\\" + st.getHinhAnh();
            lbl_images.setText("");
            ImageIcon imgIcon = new ImageIcon(url);
            Image img = imgIcon.getImage();
            lbl_images.setIcon(new ImageIcon(img.getScaledInstance(lbl_images.getWidth(), lbl_images.getHeight(), 0)));
            try {
                lbl_images.setIcon((Icon) img);
            } catch (Exception e) {
            }
        }

    }//GEN-LAST:event_tbl_studentMouseClicked

    private void formWindowDeactivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowDeactivated
//        try {
//            con.close();
//        } catch (SQLException ex) {
//            Logger.getLogger(MainGUIQuanLySinhVien.class.getName()).log(Level.SEVERE, null, ex);
//        }
    }//GEN-LAST:event_formWindowDeactivated

    private void btn_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exitActionPerformed
        String data[] = {"Đăng xuất", "Thoát", "Cancel"};
        int getChoice = JOptionPane.showOptionDialog(this, "Mời bạn chọn", "Exit", JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, null, data, EXIT_ON_CLOSE);
//        int getChoice = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn Thoát không ?", "Thoát", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (getChoice == 0) {
            try {
                new MainGUILogin().setVisible(true);
                this.dispose();
            } catch (SQLException ex) {
                Logger.getLogger(MainGUIQuanLySinhVien.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else if (getChoice == 1) {
            System.exit(0);
        }
    }//GEN-LAST:event_btn_exitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainGUIQuanLySinhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainGUIQuanLySinhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainGUIQuanLySinhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainGUIQuanLySinhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new MainGUIQuanLySinhVien().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(MainGUIQuanLySinhVien.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    public boolean checkEmpty() {
        if (txt_msv.getText().isEmpty() || txt_hoTen.getText().isEmpty() || txt_sdt.getText().isEmpty() || txt_email.getText().isEmpty() || txt_diaChi.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Mời bạn nhập đầy đủ thông tin vào các ô");
            return false;
        }
        if (txt_msv.getText().isBlank() || txt_hoTen.getText().isBlank() || txt_sdt.getText().isBlank() || txt_email.getText().isBlank() || txt_diaChi.getText().isBlank()) {
            JOptionPane.showMessageDialog(this, "Bạn không được nhập khoảng trắng vào bất kỳ ô nào \nVui lòng nhập lại");
            return false;
        }
        return true;
    }

    public void LoadTable() {
        _DefaultTableModel.setRowCount(0);
        _DefaultTableModel = (DefaultTableModel) tbl_student.getModel();
        for (Student x : _ServiceStudent.getlstStudent()) {
            _DefaultTableModel.addRow(new Object[]{x.getMsv(), x.getHoTen(), x.getEmail(), x.getSdt(), x.getGioiTinh() == true ? "Nam" : "Nữ", x.getDiaChi(), x.getHinhAnh()});
        }
    }

    public void clearForm() {
        txt_msv.setText("");
        txt_hoTen.setText("");
        txt_email.setText("");
        txt_sdt.setText("");
        txt_diaChi.setText("");
        rd_nam.setSelected(true);
        lbl_images.setIcon(null);
        lbl_images.setText("IMG (click vào đây)");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_exit;
    private javax.swing.JButton btn_new;
    private javax.swing.JButton btn_save;
    private javax.swing.JButton btn_update;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel lbl_clock;
    private javax.swing.JLabel lbl_images;
    private javax.swing.JRadioButton rd_nam;
    private javax.swing.JRadioButton rd_nu;
    private javax.swing.JTable tbl_student;
    private javax.swing.JTextArea txt_diaChi;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_hoTen;
    private javax.swing.JTextField txt_msv;
    private javax.swing.JTextField txt_sdt;
    // End of variables declaration//GEN-END:variables
}
