/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import New_Class.Grade;
import New_Class.Student;
import Service.ClockThread;
import Service.ServiceGrade;
import Service.ServiceStudent;
import java.awt.Color;
import javax.swing.JOptionPane;
import java.sql.*;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author BUI QUANG HIEU
 */
public class MainGUIQuanLyDiem extends javax.swing.JFrame {

    New_Class.Student student = new Student();
    New_Class.Grade grade = new Grade();
    Service.ServiceStudent _ServiceStudent = new ServiceStudent();
    Service.ServiceGrade _ServiceGrade = new ServiceGrade();

    /**
     * Creates new form MainGUIQuanLyDiem
     */
//    ServiceGrade _ServiceGrade = new ServiceGrade();
//    ServiceStudent _ServiceStudent = new ServiceStudent();
    Connection con;
//    List<Grade> _ListGrade = _ServiceGrade.getListGrade();
    Grade _Grade;
    DefaultTableModel _DefaultTableModel = new DefaultTableModel();
    int _index = 0, _count = 0, _count2 = 0;

    public MainGUIQuanLyDiem() throws SQLException {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        con = Connect.ketNoi("ASSIGNMENT");
        if (con != null) {
//            JOptionPane.showMessageDialog(this, "Kết nối thành công");
        } else {
            JOptionPane.showMessageDialog(this, "Kết nối không thành công");
        }
        _ServiceGrade.getListGradeDB();
        ClockThread clockThread = new ClockThread(lbl_cl);
        clockThread.start();
        if (_ServiceGrade.getListGrade().isEmpty()) {
            return;
        } else {
            txt_msv.setText(_ServiceGrade.getListGrade().get(_index).getmasv());
            txt_tiengAnh.setText(_ServiceGrade.getListGrade().get(_index).getTiengAnh() + "");
            txt_tinHoc.setText(_ServiceGrade.getListGrade().get(_index).getTinHoc() + "");
            txt_giaoDucTC.setText(_ServiceGrade.getListGrade().get(_index).getGDTC() + "");
            txt_msvFocusLost(null);
            txt_tiengAnhFocusLost(null);
        }
        top();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txt_search = new javax.swing.JTextField();
        btn_search = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_msv = new javax.swing.JTextField();
        txt_tiengAnh = new javax.swing.JTextField();
        txt_tinHoc = new javax.swing.JTextField();
        txt_giaoDucTC = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        lbl_DTB = new javax.swing.JLabel();
        lbl_ten = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_student = new javax.swing.JTable();
        btn_prev = new javax.swing.JButton();
        btn_first = new javax.swing.JButton();
        btn_last = new javax.swing.JButton();
        btn_next = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btn_new = new javax.swing.JButton();
        btn_save = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();
        btn_update = new javax.swing.JButton();
        btn_update1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        lbl_cl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản Lý Điểm Sinh Viên");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 255));
        jLabel1.setText("Quản Lý Điểm Sinh Viên");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Tìm kiếm"));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Mã SV: ");

        txt_search.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        btn_search.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Search.png"))); // NOI18N
        btn_search.setText("Search");
        btn_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_searchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel2)
                .addGap(27, 27, 27)
                .addComponent(txt_search, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addComponent(btn_search)
                .addGap(41, 41, 41))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_search))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Thêm Điểm Sinh Viên"));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Họ tên SV: ");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Mã SV:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Tiếng anh: ");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Tin học: ");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Giáo dục TC: ");

        txt_msv.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_msv.setForeground(new java.awt.Color(0, 51, 255));
        txt_msv.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_msvFocusLost(evt);
            }
        });

        txt_tiengAnh.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_tiengAnh.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_tiengAnhFocusLost(evt);
            }
        });

        txt_tinHoc.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_tinHoc.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_tinHocFocusLost(evt);
            }
        });

        txt_giaoDucTC.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_giaoDucTC.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_giaoDucTCFocusLost(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 255));
        jLabel9.setText("Điểm TB");

        lbl_DTB.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbl_DTB.setForeground(new java.awt.Color(0, 0, 255));

        lbl_ten.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_ten.setForeground(new java.awt.Color(0, 0, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel3))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_msv, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                            .addComponent(txt_tiengAnh)
                            .addComponent(txt_tinHoc)
                            .addComponent(lbl_ten, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(99, 99, 99)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_DTB, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(txt_giaoDucTC, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_ten, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txt_msv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_tiengAnh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txt_tinHoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_DTB, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txt_giaoDucTC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tbl_student.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã SV", "Họ tên", "Tiếng Anh", "Tin học", "GDTC", "Điểm TB"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_student.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_studentMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_student);

        btn_prev.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/prev.png"))); // NOI18N
        btn_prev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_prevActionPerformed(evt);
            }
        });

        btn_first.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/dau.png"))); // NOI18N
        btn_first.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_firstActionPerformed(evt);
            }
        });

        btn_last.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/cuoi.png"))); // NOI18N
        btn_last.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_lastActionPerformed(evt);
            }
        });

        btn_next.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/next.png"))); // NOI18N
        btn_next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nextActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 255));
        jLabel11.setText("3 Sinh viên có điểm cao nhất:");

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Chức năng"));

        btn_new.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_new.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Add.png"))); // NOI18N
        btn_new.setText("New");
        btn_new.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_newActionPerformed(evt);
            }
        });

        btn_save.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Save.png"))); // NOI18N
        btn_save.setText("Save");
        btn_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveActionPerformed(evt);
            }
        });

        btn_delete.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Delete.png"))); // NOI18N
        btn_delete.setText("Delete");
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });

        btn_update.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Edit.png"))); // NOI18N
        btn_update.setText("Update");
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });

        btn_update1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_update1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Exit.png"))); // NOI18N
        btn_update1.setText("Exit");
        btn_update1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_update1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_update, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_delete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_save, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_new, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btn_update1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(btn_new)
                .addGap(18, 18, 18)
                .addComponent(btn_save)
                .addGap(18, 18, 18)
                .addComponent(btn_delete)
                .addGap(18, 18, 18)
                .addComponent(btn_update)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_update1)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Clock"));
        jPanel4.setToolTipText("");

        lbl_cl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_cl.setForeground(new java.awt.Color(0, 51, 255));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_cl, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(lbl_cl, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(238, 238, 238))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_first, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_prev, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_next, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_last, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btn_first, btn_last, btn_next, btn_prev});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btn_next, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_prev, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_first, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_last, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel11)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_searchActionPerformed
        if (txt_search.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Mời bạn nhập MSV cần tìm vào ô trống !", "Thông báo", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            Student st = _ServiceStudent.findByMSV(txt_search.getText());
            if (st != null) {
//                txt_tiengAnh.setEditable(true);
//                txt_tinHoc.setEditable(true);
//                txt_giaoDucTC.setEditable(true);
                lbl_ten.setText(st.getHoTen());
                txt_msv.setText(st.getMsv());
                Grade grade = _ServiceGrade.findByMaSV(txt_search.getText());
                if (grade != null) {
                    txt_msv.setText(grade.getmasv());
                    txt_tiengAnh.setText(grade.getTiengAnh() + "");
                    txt_tinHoc.setText(grade.getTinHoc() + "");
                    txt_giaoDucTC.setText(grade.getGDTC() + "");

                    txt_msvFocusLost(null);
                    txt_tiengAnhFocusLost(null);
                } else {

                    txt_tiengAnh.setText("");
                    txt_tinHoc.setText("");
                    txt_giaoDucTC.setText("");
                    lbl_DTB.setText("");
                    JOptionPane.showMessageDialog(this, "Sinh viên này chưa có điểm !");
                }

            } else {
                lbl_ten.setText("");
                JOptionPane.showMessageDialog(this, "MSV này không có trong danh sách !", "Thông báo", JOptionPane.ERROR_MESSAGE);
//                txt_tiengAnh.setEditable(false);
//                txt_tinHoc.setEditable(false);
//                txt_giaoDucTC.setEditable(false);
                return;
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi");
        }
    }//GEN-LAST:event_btn_searchActionPerformed

    private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveActionPerformed
        try {
            Student st = _ServiceStudent.findByMSV(txt_msv.getText());
            if (st == null) {
                return;
            }
        } catch (SQLException ex) {
            Logger.getLogger(MainGUIQuanLyDiem.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (txt_msv.getText().isEmpty() || txt_tiengAnh.getText().isEmpty() || txt_tinHoc.getText().isEmpty() || txt_giaoDucTC.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Các ô không được để trống \nVui lòng điền đầy đủ thông tin", "Thông báo", JOptionPane.ERROR_MESSAGE);
            return;
        } else if (txt_msv.getText().isBlank() || txt_tiengAnh.getText().isBlank() || txt_tinHoc.getText().isBlank() || txt_giaoDucTC.getText().isBlank()) {
            JOptionPane.showMessageDialog(this, "Các ô không được để khoảng trắng \nVui lòng điền đầy đủ thông tin", "Thông báo", JOptionPane.ERROR_MESSAGE);
            return;
        } else if ((Float.parseFloat(txt_tiengAnh.getText()) < 0 || Float.parseFloat(txt_tiengAnh.getText()) > 10)
                || (Float.parseFloat(txt_tinHoc.getText()) < 0 || Float.parseFloat(txt_tinHoc.getText()) > 10)
                || (Float.parseFloat(txt_giaoDucTC.getText()) < 0 || Float.parseFloat(txt_giaoDucTC.getText()) > 10)) {
            JOptionPane.showMessageDialog(this, "Điểm phải trong khoảng 0 -10", "Thông báo", JOptionPane.ERROR_MESSAGE);
            return;
        } else {
            Grade grage = new Grade();
            grage.setmsv(txt_msv.getText().toUpperCase());
            grage.setTiengAnh(Float.parseFloat(txt_tiengAnh.getText()));
            grage.setTinHoc(Float.parseFloat(txt_tinHoc.getText()));
            grage.setGDTC(Float.parseFloat(txt_giaoDucTC.getText()));

            try {
                if (_ServiceGrade.findByMaSV(txt_msv.getText()) != null) {
                    int getChoice = JOptionPane.showConfirmDialog(this, "Sinh viên này đã có điểm \nBạn có muốn cập nhật không ?", "Cập nhật", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
                    if (getChoice == JOptionPane.YES_OPTION) {
                        if (_ServiceGrade.upDateGrade(grage)) {
                            JOptionPane.showMessageDialog(this, "Cập nhật thành công !");
                        } else {
                            JOptionPane.showMessageDialog(this, "Cập nhật không thành công");
                        }
                    }

                } else {
                    int getChoice = JOptionPane.showConfirmDialog(this, "Bạn có muốn Thêm không ?", "Thêm", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
                    if (getChoice == JOptionPane.YES_OPTION) {
                        if (_ServiceGrade.addGrade(grage)) {
                            JOptionPane.showMessageDialog(this, "Thêm thành công");

                            top();
                        } else {
                            JOptionPane.showMessageDialog(this, "Thất bại");
                        }
                    }
                }
                _ServiceGrade.getListGradeDB();
            } catch (SQLException ex) {
                Logger.getLogger(MainGUIQuanLyDiem.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btn_saveActionPerformed

    private void txt_msvFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_msvFocusLost
        try {
            Student st = _ServiceStudent.findByMSV(txt_msv.getText());
            if (st != null) {
                txt_tiengAnh.setEditable(true);
                txt_tinHoc.setEditable(true);
                txt_giaoDucTC.setEditable(true);
                lbl_ten.setText(st.getHoTen());
            } else {
                lbl_ten.setText("");
                JOptionPane.showMessageDialog(this, "MSV này không có trong danh sách !", "Thông báo", JOptionPane.ERROR_MESSAGE);
                txt_tiengAnh.setEditable(false);
                txt_tinHoc.setEditable(false);
                txt_giaoDucTC.setEditable(false);
                return;
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_txt_msvFocusLost

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        try {
            Student st = _ServiceStudent.findByMSV(txt_msv.getText());
            if (st == null) {
                return;
            }
        } catch (SQLException ex) {
            Logger.getLogger(MainGUIQuanLyDiem.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (txt_msv.getText().isEmpty() || txt_tiengAnh.getText().isEmpty() || txt_tinHoc.getText().isEmpty() || txt_giaoDucTC.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Các ô không được để trống \nVui lòng điền đầy đủ thông tin", "Thông báo", JOptionPane.ERROR_MESSAGE);
            return;
        } else if (txt_msv.getText().isBlank() || txt_tiengAnh.getText().isBlank() || txt_tinHoc.getText().isBlank() || txt_giaoDucTC.getText().isBlank()) {
            JOptionPane.showMessageDialog(this, "Các ô không được để khoảng trắng \nVui lòng điền đầy đủ thông tin", "Thông báo", JOptionPane.ERROR_MESSAGE);
            return;
        } else if ((Float.parseFloat(txt_tiengAnh.getText()) < 0 || Float.parseFloat(txt_tiengAnh.getText()) > 10)
                || (Float.parseFloat(txt_tinHoc.getText()) < 0 || Float.parseFloat(txt_tinHoc.getText()) > 10)
                || (Float.parseFloat(txt_giaoDucTC.getText()) < 0 || Float.parseFloat(txt_giaoDucTC.getText()) > 10)) {
            JOptionPane.showMessageDialog(this, "Điểm phải trong khoảng 0 -10", "Thông báo", JOptionPane.ERROR_MESSAGE);
            return;
        } else {
            int getChoice = JOptionPane.showConfirmDialog(this, "Bạn có chắn chắn Sửa không ?", "Sửa", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (getChoice == JOptionPane.YES_OPTION) {
                Grade grage = new Grade();
                grage.setmsv(txt_msv.getText());
                grage.setTiengAnh(Float.parseFloat(txt_tiengAnh.getText()));
                grage.setTinHoc(Float.parseFloat(txt_tinHoc.getText()));
                grage.setGDTC(Float.parseFloat(txt_giaoDucTC.getText()));
                try {
                    _ServiceGrade.upDateGrade(grage);

                    JOptionPane.showMessageDialog(this, "Sửa thành công !");
                    _ServiceGrade.getListGradeDB();
                    top();
                } catch (SQLException ex) {
                    Logger.getLogger(MainGUIQuanLyDiem.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showMessageDialog(this, "Thất bại");
                }
            }
        }
    }//GEN-LAST:event_btn_updateActionPerformed

    private void txt_tiengAnhFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_tiengAnhFocusLost
        if (txt_tiengAnh.getText().isEmpty() || txt_tinHoc.getText().isEmpty() || txt_giaoDucTC.getText().isEmpty()) {
            return;
        }
        float tienganh = Float.parseFloat(txt_tiengAnh.getText());
        float tinhoc = Float.parseFloat(txt_tinHoc.getText());
        float gdtc = Float.parseFloat(txt_giaoDucTC.getText());
        float dtb = (tienganh + tinhoc + gdtc) / 3;
        String st = String.format("%.2f", dtb);
        lbl_DTB.setText(st);
    }//GEN-LAST:event_txt_tiengAnhFocusLost

    private void txt_tinHocFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_tinHocFocusLost
        if (txt_tiengAnh.getText().isEmpty() || txt_tinHoc.getText().isEmpty() || txt_giaoDucTC.getText().isEmpty()) {
            return;
        }
        float tienganh = Float.parseFloat(txt_tiengAnh.getText());
        float tinhoc = Float.parseFloat(txt_tinHoc.getText());
        float gdtc = Float.parseFloat(txt_giaoDucTC.getText());
        float dtb = (tienganh + tinhoc + gdtc) / 3;
        String st = String.format("%.2f", dtb);
        lbl_DTB.setText(st);
    }//GEN-LAST:event_txt_tinHocFocusLost

    private void txt_giaoDucTCFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_giaoDucTCFocusLost
        if (txt_tiengAnh.getText().isEmpty() || txt_tinHoc.getText().isEmpty() || txt_giaoDucTC.getText().isEmpty()) {
            return;
        }
        float tienganh = Float.parseFloat(txt_tiengAnh.getText());
        float tinhoc = Float.parseFloat(txt_tinHoc.getText());
        float gdtc = Float.parseFloat(txt_giaoDucTC.getText());
        float dtb = (tienganh + tinhoc + gdtc) / 3;
        String st = String.format("%.2f", dtb);
        lbl_DTB.setText(st);
    }//GEN-LAST:event_txt_giaoDucTCFocusLost

    private void btn_newActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_newActionPerformed
        int getChoice = JOptionPane.showConfirmDialog(this, "Bạn có muốn New không ?", "New", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (getChoice == JOptionPane.YES_OPTION) {
            txt_msv.setText("");
            txt_tiengAnh.setText("");
            txt_tinHoc.setText("");
            txt_giaoDucTC.setText("");
            lbl_ten.setText("");
            lbl_DTB.setText("");
        }
    }//GEN-LAST:event_btn_newActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        try {
            Student st = _ServiceStudent.findByMSV(txt_msv.getText());
            if (st == null) {
                return;
            }
        } catch (SQLException ex) {
            Logger.getLogger(MainGUIQuanLyDiem.class.getName()).log(Level.SEVERE, null, ex);
        }
        int getChoice = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn xóa không ?", "Xóa", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (getChoice == JOptionPane.YES_OPTION) {
            try {
                _ServiceGrade.deleteGrade(txt_msv.getText());
                JOptionPane.showMessageDialog(this, "Xóa thành công !");
                top();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Xóa thất bại !");
                Logger.getLogger(MainGUIQuanLyDiem.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void btn_nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nextActionPerformed
        _index++;

        if (_index == _ServiceGrade.getListGrade().size()) {
            _index = 0;
            txt_msv.setText(_ServiceGrade.getListGrade().get(_index).getmasv());
            txt_tiengAnh.setText(_ServiceGrade.getListGrade().get(_index).getTiengAnh() + "");
            txt_tinHoc.setText(_ServiceGrade.getListGrade().get(_index).getTinHoc() + "");
            txt_giaoDucTC.setText(_ServiceGrade.getListGrade().get(_index).getGDTC() + "");
            txt_msvFocusLost(null);
            txt_tiengAnhFocusLost(null);
        } else {
            txt_msv.setText(_ServiceGrade.getListGrade().get(_index).getmasv());
            txt_tiengAnh.setText(_ServiceGrade.getListGrade().get(_index).getTiengAnh() + "");
            txt_tinHoc.setText(_ServiceGrade.getListGrade().get(_index).getTinHoc() + "");
            txt_giaoDucTC.setText(_ServiceGrade.getListGrade().get(_index).getGDTC() + "");
            txt_msvFocusLost(null);
            txt_tiengAnhFocusLost(null);

        }
    }//GEN-LAST:event_btn_nextActionPerformed

    private void btn_prevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_prevActionPerformed
        _index--;

        if (_index == -1) {
            _index = _ServiceGrade.getListGrade().size() - 1;
            txt_msv.setText(_ServiceGrade.getListGrade().get(_index).getmasv());
            txt_tiengAnh.setText(_ServiceGrade.getListGrade().get(_index).getTiengAnh() + "");
            txt_tinHoc.setText(_ServiceGrade.getListGrade().get(_index).getTinHoc() + "");
            txt_giaoDucTC.setText(_ServiceGrade.getListGrade().get(_index).getGDTC() + "");
            txt_msvFocusLost(null);
            txt_tiengAnhFocusLost(null);
        } else {
            txt_msv.setText(_ServiceGrade.getListGrade().get(_index).getmasv());
            txt_tiengAnh.setText(_ServiceGrade.getListGrade().get(_index).getTiengAnh() + "");
            txt_tinHoc.setText(_ServiceGrade.getListGrade().get(_index).getTinHoc() + "");
            txt_giaoDucTC.setText(_ServiceGrade.getListGrade().get(_index).getGDTC() + "");
            txt_msvFocusLost(null);
            txt_tiengAnhFocusLost(null);

        }
    }//GEN-LAST:event_btn_prevActionPerformed

    private void btn_firstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_firstActionPerformed
        _count++;
        _index = 0;

        txt_msv.setText(_ServiceGrade.getListGrade().get(_index).getmasv());
        txt_tiengAnh.setText(_ServiceGrade.getListGrade().get(_index).getTiengAnh() + "");
        txt_tinHoc.setText(_ServiceGrade.getListGrade().get(_index).getTinHoc() + "");
        txt_giaoDucTC.setText(_ServiceGrade.getListGrade().get(_index).getGDTC() + "");
        txt_msvFocusLost(null);
        txt_tiengAnhFocusLost(null);
        if (_count > 1) {
            JOptionPane.showMessageDialog(this, "Bạn đang ở vị trí SV đầu tiên");
            _count = 0;
        }
    }//GEN-LAST:event_btn_firstActionPerformed

    private void btn_lastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_lastActionPerformed
        _count2++;
        _index = _ServiceGrade.getListGrade().size() - 1;

        txt_msv.setText(_ServiceGrade.getListGrade().get(_index).getmasv());
        txt_tiengAnh.setText(_ServiceGrade.getListGrade().get(_index).getTiengAnh() + "");
        txt_tinHoc.setText(_ServiceGrade.getListGrade().get(_index).getTinHoc() + "");
        txt_giaoDucTC.setText(_ServiceGrade.getListGrade().get(_index).getGDTC() + "");
        txt_msvFocusLost(null);
        txt_tiengAnhFocusLost(null);
        if (_count2 > 1) {
            JOptionPane.showMessageDialog(this, "Bạn đang ở vị trí SV cuối");
            _count2 = 0;
        }
    }//GEN-LAST:event_btn_lastActionPerformed

    private void btn_update1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_update1ActionPerformed
        String data[] = {"Đăng xuất", "Thoát", "Cancel"};
        int getChoice = JOptionPane.showOptionDialog(this, "Mời bạn chọn", "Exit", JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, null, data, EXIT_ON_CLOSE);
//        int getChoice = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn Thoát không ?", "Thoát", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (getChoice == 0) {
            try {
                new MainGUILogin().setVisible(true);
                this.dispose();
            } catch (SQLException ex) {
                Logger.getLogger(MainGUIQuanLySinhVien.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else if (getChoice == 1) {
            System.exit(0);
        }
    }//GEN-LAST:event_btn_update1ActionPerformed

    private void tbl_studentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_studentMouseClicked
        int getIndex = tbl_student.getSelectedRow();
        txt_msv.setText((String) _DefaultTableModel.getValueAt(getIndex, 0));
        lbl_ten.setText((String) _DefaultTableModel.getValueAt(getIndex, 1));
        txt_tiengAnh.setText(_DefaultTableModel.getValueAt(getIndex, 2) + "");
        txt_tinHoc.setText(_DefaultTableModel.getValueAt(getIndex, 3) + "");
        txt_giaoDucTC.setText(_DefaultTableModel.getValueAt(getIndex, 4) + "");
    }//GEN-LAST:event_tbl_studentMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainGUIQuanLyDiem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainGUIQuanLyDiem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainGUIQuanLyDiem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainGUIQuanLyDiem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new MainGUIQuanLyDiem().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(MainGUIQuanLyDiem.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    public void top() {

        try {
            ServiceGrade serviceGrade = new ServiceGrade();
            List<Grade> list = serviceGrade.findTOP(3);
            _DefaultTableModel = (DefaultTableModel) tbl_student.getModel();
            _DefaultTableModel.setRowCount(0);
            for (Grade x : list) {
                _DefaultTableModel.addRow(new Object[]{x.getmasv(), _ServiceStudent.findByMSV(x.getmasv()).getHoTen(), x.getTiengAnh(), x.getTinHoc(), x.getGDTC(), String.format("%.2f", (x.getTiengAnh() + x.getTinHoc() + x.getGDTC()) / 3)});
            }
        } catch (SQLException ex) {
            Logger.getLogger(MainGUIQuanLyDiem.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_first;
    private javax.swing.JButton btn_last;
    private javax.swing.JButton btn_new;
    private javax.swing.JButton btn_next;
    private javax.swing.JButton btn_prev;
    private javax.swing.JButton btn_save;
    private javax.swing.JButton btn_search;
    private javax.swing.JButton btn_update;
    private javax.swing.JButton btn_update1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_DTB;
    private javax.swing.JLabel lbl_cl;
    private javax.swing.JLabel lbl_ten;
    private javax.swing.JTable tbl_student;
    private javax.swing.JTextField txt_giaoDucTC;
    private javax.swing.JTextField txt_msv;
    private javax.swing.JTextField txt_search;
    private javax.swing.JTextField txt_tiengAnh;
    private javax.swing.JTextField txt_tinHoc;
    // End of variables declaration//GEN-END:variables
}
